# Stage 1: Build
FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG VITE_API_BASE_URL
ARG VITE_APP_TITLE
ARG VITE_IMAGE_BASE_URL
ARG DOMAIN_OR_IP

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_APP_TITLE=$VITE_APP_TITLE
ENV VITE_IMAGE_BASE_URL=$VITE_IMAGE_BASE_URL
ENV DOMAIN_OR_IP=$DOMAIN_OR_IP

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html/custom-cake-manager
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]