server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /custom-cake-manager {
        return 301 /custom-cake-manager/;
    }

    location /custom-cake-manager/ {
        try_files $uri $uri/ /custom-cake-manager/index.html;
    }
}